from setuptools import find_packages, setup

with open('test_python_package/_version.py') as version_file:
    exec(version_file.read())

with open('README.md') as r:
    readme = r.read()

setup(
    name='test_python_package',
    version=__version__,
    description='This is an example package generated by generator-python-package.',
    long_description=readme,
    author='Hanna Torrence',
    author_email='hanna.torrence@gmail.com',
    url='https://github.com/htorrence/test_python_repo',
    license='BSD-3-Clause',
    packages=find_packages(exclude=('tests', 'docs')),
    install_requires=[
        
    ]
)
